### ISSUE TITLE
Some scripts incorrectly use "If" instead of "if"

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#11]
Find out what affect this had on the other scripts, and what fixing them will do.
Affected scripts are:

- items/swords_vb
- items/base_crystal
- items/base_kick
- items/base_scroll2
- items/smallarms_cre
- monsters/externals
- monsters/horror
- monsters/skeleton_base_old

**Comment by SaintWish** [comment]
Currently, it looks like it capitalization doesn't matter currently so both should work, since the system uses ``stricmp`` to check. 

Still though it should be changed in the future to make it standard across all scripts IMO.

**Comment by Charles445** [comment]
I think the 'old' format if (ones without parentheses) skips stricmp

This means it should at least affect

- items/base_kick
- items/smallarms_cre
- items/swords_vb
- monsters/horror

Fixing base_kick makes it so kicks only work if you do damage, which means stun and knockback aren't guaranteed, as well as preventing you from kicking friendly NPCs.
In this case I'd say the "bugged" version is more fun than the intended behavior, so I suggest commenting the line out instead of fixing it

**Comment by SaintWish** [comment]
Ah okay I see, yeah I would prefer to keep the "bugged" version of the kick as well.

**Comment by greatguys1** [comment]
As much as itd be nice, it would make no sense for the kick to do that. It has a small chance to miss anyways so youll likely hit. Itll be fixed.
