### ISSUE TITLE
Suggestion: Perfect Skull Blade Dark Damage

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/MSCScripts#124]
Title. The PSB doesn't offer anything new in its weapon lineup of skull blades (besides more damage and a huuge weight) so adding partial dark damage may be just what it needs to stand out just a little bit. It's a pretty good reward/loot drop as is, so I'm not really calling for a buff, but just a little change in its damage profile. I think that lower-level weapons are also sorely missing unique attributes or elemental damage in general, this change may help address that.

**Comment by greatguys1** [comment]
This would be better suited as a suggestion in the discord. We have a forum there that opens the topic up to the community to allow them to give input. 

On the note of weapon variants, like the skull blade as you mentioned, hugger dagger, finely crafted knife, katanas, folded steel blade, all of the low level bows... and more probably... they are problematic in my opinion, since they add no flavor to the game or weapons.

**Comment by frendship-loost** [comment]
Ok will close and post in Discord instead.
