### ISSUE TITLE
Player Can Deposit Some Perishable Items Into Galat Chest

### ISSUE THREAD

**Issue by PHILLIPGATLIN** [MSRevive/MSCScripts#163]
I was able to deposit a speed potion into my Galat storage chest despite the game notifying me that you cannot deposit a perishable item when I attempted to deposit a Poison Aura Potion.

**Comment by greatguys1** [comment]
This is not a bug, some single use potions do not use the "quality" property, which tracks how many uses are left on a potion. This does not get saved on the chest if it were to be deposited, but since something like the speed potion doesn't use it, it'll have no issues being deposited.
I should note that it is planned for galats to be able to store ammo and "quality" items.
