### ISSUE TITLE
Sometimes keledros will not transform to his second stage, breaking the fight

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#206]

**Comment by greatguys1** [comment]
This happens if you hit him with a holy dot.

**Comment by CrashWolf** [comment]
In my experience, it happens with any holy damage, regardless of whether it's a dot or not. Just hitting him with fshard in holy mode breaks him.
It's because he (probably) uses the same logic as the standard skeletons for getting back up, and any holy damage will prevent that. Just swap him and the skeletal archers in nightmare_edana lmao

On a related note, the whatshisbutt guardian of the labyrinth on aleyesu also suffers this bug (although that's not an issue because the key is spawned as soon as the human form dies, making the skeleton fight completely pointless)
