### ISSUE TITLE
Foutpost End Sequence Broken

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#221]
I'm not sure if it's due to the duplicate Vadrels (see: https://github.com/MSRevive/MSCScripts/issues/220 ), but for whatever reason, the map cannot be completed. Upon killing the orc boss at the end of the cave, the pop-up states we should return the orc's head to the supervisor of the outpost. 

Speaking to the supervisor, he has no option to complete the event. Hailing him only causes him to reply his thank-you message for saving the outpost, yet things such as bloodstone ring quest and the loot room cannot proceed.

https://steamuserimages-a.akamaihd.net/ugc/2008073659338891443/9B22A8564AAFE4E8725D69B768829603FEA77A32/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

https://steamuserimages-a.akamaihd.net/ugc/2008073659338891885/2A4FC99FC68CB655843E5236FF7FE500A00576DE/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Drathamus** [comment]
On further investigation:

If the orc boss drops his great axe, he will not drop the head required to turn in to Vadrel to finish the map.

**Comment by greatguys1** [comment]
To clarify, the orc boss should drop his head when he's killed. If no one brings Vadrel the head, he says some confusing dialogue that makes the player think they're done. If they do bring him the head, then the players are rewarded as normal.

So the current standing issue is that the orc boss will not drop his head if he drops his axe.

The duplicate Vadrels mentioned in the other issue shouldn't be causing this issue here.

**Comment by greatguys1** [comment]
I tested and both items spawned correctly. Will mark the issue as will not complete if cannot replicate.
