### ISSUE TITLE
Erratic lightning's second strike after summoning it fails to do damage

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#41]

**Comment by Charles445** [comment]
script.ramp is not properly initialized, so at some point damage is multiplied by 0 (causing the bug), and ramping damage starts there instead of at 1 like it's supposed to

Quick fix for this is to add
`if( script.ramp startswith 'script' ) setvard script.ramp 1`
At the beginning of cast_damaged_other in items/magic_hand_lightning_weak.script

**Comment by greatguys1** [comment]
Fixed in https://github.com/MSRevive/MSCScripts/pull/83
