### ISSUE TITLE
Equipping armor shows displays 2 % signs in the combat log

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#68]
![image](https://user-images.githubusercontent.com/24220703/178126810-f9278c2b-9ccf-466e-b6b6-c1288e7d87ac.png)

**Comment by greatguys1** [comment]
Happens with all armor, probably a base armor issue

**Comment by Charles445** [comment]
Pretty sure this is due to playermessagecl not being run through string format anymore
https://github.com/MSRevive/MasterSwordRebirth/blob/dev/game/shared/weapons/genericitem.cpp#L1879
So %% is no longer %

Just need to remove the extra %
https://github.com/MSRevive/MSCScripts/blob/MSCScript-alpha/scripts/items/armor_base.script#L92

**Comment by greatguys1** [comment]
Fixed in https://github.com/MSRevive/MSCScripts/pull/83
